# Generated by Django 2.2.4 on 2021-02-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='like',
            field=models.ManyToManyField(related_name='liked', to='app.User'),
        ),
    ]
